<?php
/**
 * Aarunya Healthcare - Theme Customizer
 * Change the entire UI color scheme with a single click
 */

session_start();

// Helper function to convert hex to RGB
function hexToRgb($hex) {
    $hex = str_replace('#', '', $hex);
    if (strlen($hex) == 3) {
        $r = hexdec(substr($hex, 0, 1) . substr($hex, 0, 1));
        $g = hexdec(substr($hex, 1, 1) . substr($hex, 1, 1));
        $b = hexdec(substr($hex, 2, 1) . substr($hex, 2, 1));
    } else {
        $r = hexdec(substr($hex, 0, 2));
        $g = hexdec(substr($hex, 2, 2));
        $b = hexdec(substr($hex, 4, 2));
    }
    return "$r, $g, $b";
}

// Handle theme save
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_theme'])) {
    $themeData = [
        'primary_color' => $_POST['primary_color'] ?? '#667eea',
        'secondary_color' => $_POST['secondary_color'] ?? '#764ba2',
        'accent_color' => $_POST['accent_color'] ?? '#00D1FF',
        'success_color' => $_POST['success_color'] ?? '#10b981',
        'warning_color' => $_POST['warning_color'] ?? '#f59e0b',
        'danger_color' => $_POST['danger_color'] ?? '#ef4444',
        'background_color' => $_POST['background_color'] ?? '#0F172A',
        'card_background' => $_POST['card_background'] ?? 'rgba(30, 41, 59, 0.6)',
        'text_primary' => $_POST['text_primary'] ?? '#ffffff',
        'text_secondary' => $_POST['text_secondary'] ?? '#94a3b8',
    ];
    
    // Save to CSS file
    $cssContent = ":root {\n";
    $cssContent .= "    /* Theme Colors - Generated by Theme Customizer */\n";
    $cssContent .= "    /* These override the default colors in premium-design-system.css */\n";
    $cssContent .= "    --primary-purple: {$themeData['primary_color']} !important;\n";
    $cssContent .= "    --secondary-purple: {$themeData['secondary_color']} !important;\n";
    $cssContent .= "    --primary-deep: {$themeData['secondary_color']} !important;\n";
    $cssContent .= "    --accent-cyan: {$themeData['accent_color']} !important;\n";
    $cssContent .= "    --success: {$themeData['success_color']} !important;\n";
    $cssContent .= "    --warning: {$themeData['warning_color']} !important;\n";
    $cssContent .= "    --danger: {$themeData['danger_color']} !important;\n";
    $cssContent .= "    --bg-dark: {$themeData['background_color']} !important;\n";
    
    // Calculate darker background
    $bgColor = $themeData['background_color'];
    $darkerBg = $bgColor; // You can adjust this if needed
    $cssContent .= "    --bg-darker: $darkerBg !important;\n";
    
    $cssContent .= "    --text-primary: {$themeData['text_primary']} !important;\n";
    $cssContent .= "    --text-secondary: {$themeData['text_secondary']} !important;\n";
    $cssContent .= "    --text-muted: {$themeData['text_secondary']} !important;\n";
    $cssContent .= "    \n";
    $cssContent .= "    /* Gradient Backgrounds */\n";
    $cssContent .= "    --gradient-hero: linear-gradient(135deg, {$themeData['primary_color']} 0%, {$themeData['secondary_color']} 100%) !important;\n";
    $cssContent .= "    --gradient-button: linear-gradient(135deg, {$themeData['primary_color']} 0%, {$themeData['secondary_color']} 100%) !important;\n";
    $cssContent .= "    --gradient-card: linear-gradient(145deg, rgba(" . hexToRgb($themeData['primary_color']) . ", 0.15), rgba(" . hexToRgb($themeData['secondary_color']) . ", 0.08)) !important;\n";
    $cssContent .= "    --gradient-sidebar: linear-gradient(180deg, {$themeData['background_color']} 0%, $darkerBg 100%) !important;\n";
    $cssContent .= "    --bg-sidebar: linear-gradient(180deg, {$themeData['background_color']} 0%, $darkerBg 100%) !important;\n";
    $cssContent .= "}\n";
    
    // Save to file
    file_put_contents(__DIR__ . '/client/styles/theme-custom.css', $cssContent);
    
    $_SESSION['theme_message'] = 'Theme saved successfully! <strong>Please clear your browser cache (Ctrl+Shift+Delete) and hard refresh (Ctrl+F5) to see changes.</strong>';
    header('Location: theme_customizer.php');
    exit;
}

// Preset themes
$presetThemes = [
    'default' => [
        'name' => 'Purple Dream (Default)',
        'primary_color' => '#667eea',
        'secondary_color' => '#764ba2',
        'accent_color' => '#00D1FF',
        'success_color' => '#10b981',
        'warning_color' => '#f59e0b',
        'danger_color' => '#ef4444',
        'background_color' => '#0F172A',
        'card_background' => 'rgba(30, 41, 59, 0.6)',
        'text_primary' => '#ffffff',
        'text_secondary' => '#94a3b8',
    ],
    'ocean' => [
        'name' => 'Ocean Blue',
        'primary_color' => '#0ea5e9',
        'secondary_color' => '#0284c7',
        'accent_color' => '#06b6d4',
        'success_color' => '#10b981',
        'warning_color' => '#f59e0b',
        'danger_color' => '#ef4444',
        'background_color' => '#0c4a6e',
        'card_background' => 'rgba(7, 89, 133, 0.6)',
        'text_primary' => '#ffffff',
        'text_secondary' => '#bae6fd',
    ],
    'forest' => [
        'name' => 'Forest Green',
        'primary_color' => '#10b981',
        'secondary_color' => '#059669',
        'accent_color' => '#34d399',
        'success_color' => '#22c55e',
        'warning_color' => '#f59e0b',
        'danger_color' => '#ef4444',
        'background_color' => '#064e3b',
        'card_background' => 'rgba(6, 78, 59, 0.6)',
        'text_primary' => '#ffffff',
        'text_secondary' => '#a7f3d0',
    ],
    'sunset' => [
        'name' => 'Sunset Orange',
        'primary_color' => '#f97316',
        'secondary_color' => '#ea580c',
        'accent_color' => '#fb923c',
        'success_color' => '#10b981',
        'warning_color' => '#fbbf24',
        'danger_color' => '#ef4444',
        'background_color' => '#7c2d12',
        'card_background' => 'rgba(124, 45, 18, 0.6)',
        'text_primary' => '#ffffff',
        'text_secondary' => '#fed7aa',
    ],
    'rose' => [
        'name' => 'Rose Pink',
        'primary_color' => '#ec4899',
        'secondary_color' => '#db2777',
        'accent_color' => '#f472b6',
        'success_color' => '#10b981',
        'warning_color' => '#f59e0b',
        'danger_color' => '#ef4444',
        'background_color' => '#831843',
        'card_background' => 'rgba(131, 24, 67, 0.6)',
        'text_primary' => '#ffffff',
        'text_secondary' => '#fbcfe8',
    ],
    'midnight' => [
        'name' => 'Midnight Blue',
        'primary_color' => '#3b82f6',
        'secondary_color' => '#2563eb',
        'accent_color' => '#60a5fa',
        'success_color' => '#10b981',
        'warning_color' => '#f59e0b',
        'danger_color' => '#ef4444',
        'background_color' => '#1e3a8a',
        'card_background' => 'rgba(30, 58, 138, 0.6)',
        'text_primary' => '#ffffff',
        'text_secondary' => '#bfdbfe',
    ],
    'lavender' => [
        'name' => 'Lavender Dream',
        'primary_color' => '#a78bfa',
        'secondary_color' => '#8b5cf6',
        'accent_color' => '#c4b5fd',
        'success_color' => '#10b981',
        'warning_color' => '#f59e0b',
        'danger_color' => '#ef4444',
        'background_color' => '#5b21b6',
        'card_background' => 'rgba(91, 33, 182, 0.6)',
        'text_primary' => '#ffffff',
        'text_secondary' => '#ddd6fe',
    ],
    'crimson' => [
        'name' => 'Crimson Red',
        'primary_color' => '#dc2626',
        'secondary_color' => '#b91c1c',
        'accent_color' => '#f87171',
        'success_color' => '#10b981',
        'warning_color' => '#f59e0b',
        'danger_color' => '#991b1b',
        'background_color' => '#7f1d1d',
        'card_background' => 'rgba(127, 29, 29, 0.6)',
        'text_primary' => '#ffffff',
        'text_secondary' => '#fecaca',
    ],
];

$message = $_SESSION['theme_message'] ?? '';
unset($_SESSION['theme_message']);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Theme Customizer - Aarunya Healthcare</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
        }
        
        .header {
            background: white;
            border-radius: 20px;
            padding: 30px;
            margin-bottom: 30px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        }
        
        .header h1 {
            color: #667eea;
            font-size: 2.5rem;
            margin-bottom: 10px;
        }
        
        .header p {
            color: #666;
            font-size: 1.1rem;
        }
        
        .success-message {
            background: #d4edda;
            color: #155724;
            padding: 15px 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
            animation: slideIn 0.3s ease-out;
        }
        
        @keyframes slideIn {
            from {
                opacity: 0;
                transform: translateY(-20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        .content {
            display: grid;
            grid-template-columns: 1fr 400px;
            gap: 30px;
        }
        
        .presets-section {
            background: white;
            border-radius: 20px;
            padding: 30px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        }
        
        .presets-section h2 {
            color: #333;
            font-size: 1.8rem;
            margin-bottom: 20px;
        }
        
        .presets-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 20px;
        }
        
        .preset-card {
            border: 2px solid #e5e7eb;
            border-radius: 15px;
            padding: 20px;
            cursor: pointer;
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
        }
        
        .preset-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
            border-color: #667eea;
        }
        
        .preset-preview {
            height: 100px;
            border-radius: 10px;
            margin-bottom: 15px;
            position: relative;
        }
        
        .preset-name {
            font-weight: 600;
            color: #333;
            text-align: center;
            font-size: 0.95rem;
        }
        
        .color-dots {
            display: flex;
            justify-content: center;
            gap: 5px;
            margin-top: 10px;
        }
        
        .color-dot {
            width: 20px;
            height: 20px;
            border-radius: 50%;
            border: 2px solid white;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
        }
        
        .custom-section {
            background: white;
            border-radius: 20px;
            padding: 30px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            position: sticky;
            top: 20px;
        }
        
        .custom-section h2 {
            color: #333;
            font-size: 1.8rem;
            margin-bottom: 20px;
        }
        
        .color-input-group {
            margin-bottom: 20px;
        }
        
        .color-input-group label {
            display: block;
            font-weight: 600;
            color: #333;
            margin-bottom: 8px;
            font-size: 0.9rem;
        }
        
        .color-input-wrapper {
            display: flex;
            gap: 10px;
            align-items: center;
        }
        
        .color-input-wrapper input[type="color"] {
            width: 60px;
            height: 40px;
            border: 2px solid #e5e7eb;
            border-radius: 8px;
            cursor: pointer;
        }
        
        .color-input-wrapper input[type="text"] {
            flex: 1;
            padding: 10px 15px;
            border: 2px solid #e5e7eb;
            border-radius: 8px;
            font-size: 0.9rem;
            font-family: monospace;
        }
        
        .btn {
            padding: 15px 30px;
            border: none;
            border-radius: 10px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s ease;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
        }
        
        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            width: 100%;
        }
        
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4);
        }
        
        .btn-secondary {
            background: #6c757d;
            color: white;
            width: 100%;
            margin-top: 10px;
        }
        
        .btn-secondary:hover {
            background: #5a6268;
        }
        
        .preview-section {
            background: white;
            border-radius: 20px;
            padding: 30px;
            margin-top: 30px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        }
        
        .preview-section h2 {
            color: #333;
            font-size: 1.8rem;
            margin-bottom: 20px;
        }
        
        .preview-components {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
        }
        
        .preview-card {
            padding: 20px;
            border-radius: 10px;
            border: 2px solid #e5e7eb;
        }
        
        .preview-button {
            padding: 10px 20px;
            border: none;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            width: 100%;
            margin-bottom: 10px;
        }
        
        @media (max-width: 1024px) {
            .content {
                grid-template-columns: 1fr;
            }
            
            .custom-section {
                position: static;
            }
        }
        
        @media (max-width: 768px) {
            .presets-grid {
                grid-template-columns: 1fr;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1><i class="fas fa-palette"></i> Theme Customizer</h1>
            <p>Change the entire UI color scheme of Aarunya Healthcare with a single click</p>
        </div>

        <?php if ($message): ?>
        <div class="success-message">
            <i class="fas fa-check-circle"></i>
            <span><?php echo htmlspecialchars($message); ?></span>
        </div>
        <?php endif; ?>

        <div class="content">
            <!-- Preset Themes -->
            <div class="presets-section">
                <h2><i class="fas fa-swatchbook"></i> Preset Themes</h2>
                <p style="color: #666; margin-bottom: 20px;">Click on any theme to apply it instantly</p>
                
                <div class="presets-grid">
                    <?php foreach ($presetThemes as $key => $theme): ?>
                    <div class="preset-card" onclick="applyPreset('<?php echo $key; ?>')">
                        <div class="preset-preview" style="background: linear-gradient(135deg, <?php echo $theme['primary_color']; ?> 0%, <?php echo $theme['secondary_color']; ?> 100%);">
                        </div>
                        <div class="preset-name"><?php echo $theme['name']; ?></div>
                        <div class="color-dots">
                            <div class="color-dot" style="background: <?php echo $theme['primary_color']; ?>;"></div>
                            <div class="color-dot" style="background: <?php echo $theme['secondary_color']; ?>;"></div>
                            <div class="color-dot" style="background: <?php echo $theme['accent_color']; ?>;"></div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <!-- Custom Colors -->
            <div class="custom-section">
                <h2><i class="fas fa-paint-brush"></i> Custom Colors</h2>
                <p style="color: #666; margin-bottom: 20px;">Create your own custom theme</p>
                
                <form method="POST" id="customThemeForm">
                    <input type="hidden" name="save_theme" value="1">
                    
                    <div class="color-input-group">
                        <label>Primary Color</label>
                        <div class="color-input-wrapper">
                            <input type="color" name="primary_color" id="primary_color" value="#667eea" onchange="updateTextInput(this)">
                            <input type="text" id="primary_color_text" value="#667eea" onchange="updateColorInput(this, 'primary_color')">
                        </div>
                    </div>

                    <div class="color-input-group">
                        <label>Secondary Color</label>
                        <div class="color-input-wrapper">
                            <input type="color" name="secondary_color" id="secondary_color" value="#764ba2" onchange="updateTextInput(this)">
                            <input type="text" id="secondary_color_text" value="#764ba2" onchange="updateColorInput(this, 'secondary_color')">
                        </div>
                    </div>

                    <div class="color-input-group">
                        <label>Accent Color</label>
                        <div class="color-input-wrapper">
                            <input type="color" name="accent_color" id="accent_color" value="#00D1FF" onchange="updateTextInput(this)">
                            <input type="text" id="accent_color_text" value="#00D1FF" onchange="updateColorInput(this, 'accent_color')">
                        </div>
                    </div>

                    <div class="color-input-group">
                        <label>Success Color</label>
                        <div class="color-input-wrapper">
                            <input type="color" name="success_color" id="success_color" value="#10b981" onchange="updateTextInput(this)">
                            <input type="text" id="success_color_text" value="#10b981" onchange="updateColorInput(this, 'success_color')">
                        </div>
                    </div>

                    <div class="color-input-group">
                        <label>Warning Color</label>
                        <div class="color-input-wrapper">
                            <input type="color" name="warning_color" id="warning_color" value="#f59e0b" onchange="updateTextInput(this)">
                            <input type="text" id="warning_color_text" value="#f59e0b" onchange="updateColorInput(this, 'warning_color')">
                        </div>
                    </div>

                    <div class="color-input-group">
                        <label>Danger Color</label>
                        <div class="color-input-wrapper">
                            <input type="color" name="danger_color" id="danger_color" value="#ef4444" onchange="updateTextInput(this)">
                            <input type="text" id="danger_color_text" value="#ef4444" onchange="updateColorInput(this, 'danger_color')">
                        </div>
                    </div>

                    <div class="color-input-group">
                        <label>Background Color</label>
                        <div class="color-input-wrapper">
                            <input type="color" name="background_color" id="background_color" value="#0F172A" onchange="updateTextInput(this)">
                            <input type="text" id="background_color_text" value="#0F172A" onchange="updateColorInput(this, 'background_color')">
                        </div>
                    </div>

                    <input type="hidden" name="card_background" value="rgba(30, 41, 59, 0.6)">
                    <input type="hidden" name="text_primary" value="#ffffff">
                    <input type="hidden" name="text_secondary" value="#94a3b8">

                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-save"></i>
                        <span>Save Custom Theme</span>
                    </button>

                    <button type="button" class="btn btn-secondary" onclick="resetToDefault()">
                        <i class="fas fa-undo"></i>
                        <span>Reset to Default</span>
                    </button>
                </form>
            </div>
        </div>

        <!-- Preview Section -->
        <div class="preview-section">
            <h2><i class="fas fa-eye"></i> Live Preview</h2>
            <p style="color: #666; margin-bottom: 20px;">See how your theme looks</p>
            
            <div class="preview-components">
                <div class="preview-card">
                    <h3 style="margin-bottom: 15px;">Buttons</h3>
                    <button class="preview-button" id="preview-primary" style="background: #667eea; color: white;">Primary Button</button>
                    <button class="preview-button" id="preview-secondary" style="background: #764ba2; color: white;">Secondary Button</button>
                    <button class="preview-button" id="preview-accent" style="background: #00D1FF; color: white;">Accent Button</button>
                </div>

                <div class="preview-card">
                    <h3 style="margin-bottom: 15px;">Status Colors</h3>
                    <button class="preview-button" id="preview-success" style="background: #10b981; color: white;">Success</button>
                    <button class="preview-button" id="preview-warning" style="background: #f59e0b; color: white;">Warning</button>
                    <button class="preview-button" id="preview-danger" style="background: #ef4444; color: white;">Danger</button>
                </div>

                <div class="preview-card" id="preview-background" style="background: #0F172A; color: white;">
                    <h3 style="margin-bottom: 15px;">Background</h3>
                    <p>This shows how the background color will look in your application.</p>
                </div>
            </div>
        </div>
    </div>

    <script>
        const presetThemes = <?php echo json_encode($presetThemes); ?>;

        function updateTextInput(colorInput) {
            const textInput = document.getElementById(colorInput.id + '_text');
            textInput.value = colorInput.value;
            updatePreview();
        }

        function updateColorInput(textInput, colorInputId) {
            const colorInput = document.getElementById(colorInputId);
            colorInput.value = textInput.value;
            updatePreview();
        }

        function updatePreview() {
            const primary = document.getElementById('primary_color').value;
            const secondary = document.getElementById('secondary_color').value;
            const accent = document.getElementById('accent_color').value;
            const success = document.getElementById('success_color').value;
            const warning = document.getElementById('warning_color').value;
            const danger = document.getElementById('danger_color').value;
            const background = document.getElementById('background_color').value;

            document.getElementById('preview-primary').style.background = primary;
            document.getElementById('preview-secondary').style.background = secondary;
            document.getElementById('preview-accent').style.background = accent;
            document.getElementById('preview-success').style.background = success;
            document.getElementById('preview-warning').style.background = warning;
            document.getElementById('preview-danger').style.background = danger;
            document.getElementById('preview-background').style.background = background;
        }

        function applyPreset(presetKey) {
            const theme = presetThemes[presetKey];
            
            document.getElementById('primary_color').value = theme.primary_color;
            document.getElementById('primary_color_text').value = theme.primary_color;
            
            document.getElementById('secondary_color').value = theme.secondary_color;
            document.getElementById('secondary_color_text').value = theme.secondary_color;
            
            document.getElementById('accent_color').value = theme.accent_color;
            document.getElementById('accent_color_text').value = theme.accent_color;
            
            document.getElementById('success_color').value = theme.success_color;
            document.getElementById('success_color_text').value = theme.success_color;
            
            document.getElementById('warning_color').value = theme.warning_color;
            document.getElementById('warning_color_text').value = theme.warning_color;
            
            document.getElementById('danger_color').value = theme.danger_color;
            document.getElementById('danger_color_text').value = theme.danger_color;
            
            document.getElementById('background_color').value = theme.background_color;
            document.getElementById('background_color_text').value = theme.background_color;
            
            updatePreview();
            
            // Auto-submit form
            document.getElementById('customThemeForm').submit();
        }

        function resetToDefault() {
            applyPreset('default');
        }

        // Initialize preview
        updatePreview();
    </script>
</body>
</html>
